"""Schemas module for Pydantic models."""

from app.schemas.auth import (
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    Token,
    TokenData,
    UserUpdate,
    PasswordChange,
    MagicLinkRequest,
    MagicLinkResponse,
)
from app.schemas.project import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectListResponse,
)
from app.schemas.milestone import (
    MilestoneBase,
    MilestoneCreate,
    MilestoneUpdate,
    MilestoneSubmit,
    MilestoneApprove,
    MilestoneResponse,
    MilestoneListResponse,
)
from app.schemas.transaction import (
    TransactionBase,
    TransactionCreate,
    EscrowHoldRequest,
    EscrowReleaseRequest,
    TransactionResponse,
    TransactionListResponse,
)
from app.schemas.kyc import KycBase, KycCreate, KycResponse, KycUpdate, KycApproval
from app.schemas.wallet import (
    WalletProvider,
    WalletEventType,
    WalletRegistryBase,
    WalletRegistryCreate,
    WalletRegistryResponse,
    WalletRegistryListResponse,
    WalletBalanceSnapshotBase,
    WalletBalanceSnapshotCreate,
    WalletBalanceSnapshotResponse,
    WalletBalanceSnapshotListResponse,
    WalletTransactionEventBase,
    WalletTransactionEventCreate,
    WalletTransactionEventResponse,
    WalletTransactionEventListResponse,
    WalletSyncRequest,
    WalletGetBalanceRequest,
)
from app.schemas.fincra import (
    FinCraPaymentRequest,
    FinCraPaymentResponse,
    FinCraPaymentVerifyRequest,
    FinCraPaymentVerifyResponse,
    FinCraTransferRequest,
    FinCraTransferResponse,
    FinCraTransferVerifyRequest,
    FinCraTransferVerifyResponse,
    FinCraBalanceRequest,
    FinCraBalanceResponse,
)

__all__ = [
    # Auth schemas
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenData",
    "UserUpdate",
    "PasswordChange",
    "MagicLinkRequest",
    "MagicLinkResponse",
    # Project schemas
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    # Milestone schemas
    "MilestoneBase",
    "MilestoneCreate",
    "MilestoneUpdate",
    "MilestoneSubmit",
    "MilestoneApprove",
    "MilestoneResponse",
    "MilestoneListResponse",
    # Transaction schemas
    "TransactionBase",
    "TransactionCreate",
    "EscrowHoldRequest",
    "EscrowReleaseRequest",
    "TransactionResponse",
    "TransactionListResponse",
    # KYC schemas
    "KycBase",
    "KycCreate",
    "KycResponse",
    "KycUpdate",
    "KycApproval",
    # Wallet schemas
    "WalletProvider",
    "WalletEventType",
    "WalletRegistryBase",
    "WalletRegistryCreate",
    "WalletRegistryResponse",
    "WalletRegistryListResponse",
    "WalletBalanceSnapshotBase",
    "WalletBalanceSnapshotCreate",
    "WalletBalanceSnapshotResponse",
    "WalletBalanceSnapshotListResponse",
    "WalletTransactionEventBase",
    "WalletTransactionEventCreate",
    "WalletTransactionEventResponse",
    "WalletTransactionEventListResponse",
    "WalletSyncRequest",
    "WalletGetBalanceRequest",
    # FinCra schemas
    "FinCraPaymentRequest",
    "FinCraPaymentResponse",
    "FinCraPaymentVerifyRequest",
    "FinCraPaymentVerifyResponse",
    "FinCraTransferRequest",
    "FinCraTransferResponse",
    "FinCraTransferVerifyRequest",
    "FinCraTransferVerifyResponse",
    "FinCraBalanceRequest",
    "FinCraBalanceResponse",
]
